version: 2.1
orbs:
  python: circleci/python@2.1.1
  win: circleci/windows@5.0
  macos: circleci/macos@2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create-cli-mac:
    macos:
      xcode: 13.4.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Installs
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install portaudio
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build Mac CLI
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install python@3.10
            sudo pip3 install pyobjc
            cd build/mac
            ./build_mac.sh
            ls
      - store_artifacts:
          path: dist/dfm
          destination: cli-mac  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  create-cli:
    jobs:
      - create-cli-mac
       # filter on main
